import { makeStyles } from "@material-ui/core";
// import image from "../../../../public/assets/"
import bg from "../CustomeHook/home-bg.jpeg";
const useStyle = makeStyles(() => ({
  input: {
    background: "#333",
    borderRadius: "4px",
    border: "0",
    color: "#fff",
    height: "50px",
    lineHeight: "50px",
    padding: "5px 20px",
    marginBottom: "20px",
  },
  title: {
    color: "#fff",
    fontSize: "32px",
    fontWeight: "bold",
    marginBottom: "28px",
  },
  wrapper: {
    display: "flex",
    flexDirection: "column",
    minHeight: "570px",
    backgroundColor: "rgba(0, 0, 0, 0.75)",
    borderRadius: "5px",
    width: "100%",
    margin: "auto",
    maxWidth: "450px",
    padding: "60px 68px 40px",
    marginBottom: "100px",
  },
  base: {
    display: "flex",
    flexDirection: "column",
    maxWidth: "450px",
    width: "100%",
  },
  Button: {
    background: "#e50914",
    borderRadius: "4px",
    fontSize: "16px",
    fontWeight: "bold",
    margin: "0 0 12px",
    padding: "16px",
    border: "0",
    color: "white",
    cursor: "pointer",
  },
  text: {
    color: "#8c8c8c",
    fontSize: "16px",
    fontWeight: "500",
  },
  link: {
    color: "#fff",
    textDecoration: "none",
    marginRight: "30px",
    cursor: "pointer",
    textDecoration: "none",
    marginLeft: "5px",
  },
  navBar: {
    maxWidth: "1850px",
    width: "100%",
    display: "flex",
    justifyContent: "space-between",
    marginBottom: "175px",
    marginRight: "auto",
    marginLeft: "auto",
  },
  home: {
    background: `url(${bg})`,
    backgroundPosition: "top left",
    backgroundSize: "cover",
    backgroundRepeat: "no-repeat",
    padding: "30px 50px",
  },
  navbarHome: {
    maxWidth: "1850px",
    width: "100%",
    display: "flex",
    justifyContent: "space-between",
    marginBottom: "175px",
    marginBight: "auto",
    marginLeft: "auto",
  },

  navbarSignin: {
    marginBottom: "75px",
  },
  logo: {
    height: "32px",
    width: "108px",
  },

  signinButton: {
    display: "block",
    backgroundColor: "#e50914",
    width: "84px",
    height: "fit-content",
    color: "#fff",
    border: "0",
    fontSize: "15px",
    borderRadius: "3px",
    padding: "8px 17px",
    cursor: "pointer",
  },

  headerLink: {
    padding: "5px",
  },

  link: {
    color: "#fff",
    marginLeft: "25px",
    cursor: "pointer",
  },

  wrapperHome: {
    textAlign: "center",
  },

  titleHome: {
    color: "white",
    maxWidth: "640px",
    fontSize: "50px",
    fontWeight: "700",
    margin: "auto",
  },
  optformButton: {
    width: "fit-content",
    height: "60px",
    background: "#e50914",
    color: "#fff",
    textTransform: "uppercase",
    padding: "0 32px",
    fontSize: "26px",
    border: " 0",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
  },
  formEmail: {
    maxWidth: "450px",
    width: "100%",
    border: "1",
    borderColor: "white",
    padding: "10px",
    height: "1.1876em",
    fontSize: "20px",
  },
  formWrapper: {
    display: "flex",
    justifyContent: "center",
    marginTop: "20px",
    marginBottom: "70px",
    padding: "0 20px",
  },
  formText: {
    fontSize: "19px",
    color: "#fff",
    textAlign: "center",
    padding: "0 20px",
  },
  contentTitle: {
    fontSize: "3rem",
    lineHeight: "1.1",
    marginBottom: "8px",
    paddingRight: "100px",
    color: "#fff",
  },
  contentSubTitle: {
    fontSize: "1.5rem",
    fontWeight: "normal",
    lineHeight: "normal",
    paddingRight: "100px",
    color: "#fff",
  },
  ContentImage: {
    maxWidth: "100%",
    height: "auto",
  },
  ContentItem: {
    padding: "70px 5%",
    maxWidth: "100%",
    margin: "auto",
    display: "flex",
    justifyContent: "flex-end",
    borderBottom: "4px solid #222",
  },
  textContent: {
    boxSizing: "border-box",
  },
}));
export default useStyle;
